language: cpp

sudo: false

services:
  - rabbitmq

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - g++-5-multilib
      - linux-libc-dev
      - libboost1.55-all-dev
      - liblua5.1-0
      - lua5.1
      - luarocks
      - librabbitmq-dev

cache:
  - apt

before_script:
  - export CXX="g++-5"
  - export AMQP_BROKER="localhost"
  - ./build_rabbitmq
  - luarocks --local install busted

script:
  - export LD_LIBRARY_PATH=`pwd`/tmp_build/librabbitmq #:$LD_LIBRARY_PATH:/usr/local/lib/i386-linux-gnu
  - make -C Build/linux/gmake config=release_x64
  - ~/.luarocks/bin/busted test/test_connection.lua
  - ~/.luarocks/bin/busted test/test_channels.lua
  - ~/.luarocks/bin/busted test/test_ack.lua
  - ~/.luarocks/bin/busted test/test_consume.lua
  - ~/.luarocks/bin/busted test/test_exchange.lua
  - ~/.luarocks/bin/busted test/test_get.lua
  - ~/.luarocks/bin/busted test/test_message.lua
  - ~/.luarocks/bin/busted test/test_publish.lua
